import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import RootLayout from '../Layout/RootLayout'

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Word!</h1>
        <h2>
          Welcome <a href="#">Rafael Pilartes!</a>
        </h2>
        <h3>Tchossy Solution</h3>
      </main>
    </div>
  )
}

Home.layout = RootLayout

export default Home
